### ISSUE TITLE
Messages on unknown channel lead to failure

### ISSUE THREAD

**Issue by jonathanverner** [mozilla/authenticator-rs#100]
The ctap over hid protocol spec allows for different applications to
communicate with the authenticator at the same time. This is done by
allocating a "channel" for each application. An application should
ignore messages coming on channels it does not know.
(see
https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#usb-channels).
However, authenticator-rs is confused when a message on an unexpected channel arrives.

See also https://bugs.chromium.org/p/chromium/issues/detail?id=998452
for a similar bug which was fixed in chrome.

The problem seems to be in the `U2FHIDInit` and `U2FHIDCont` functions where a message on a different channel leads to failure when checking the channel id (on line 46 and 106 respectively):

```rust
        if dev.get_cid() != &frame[..4] {
            return Err(io_err("invalid channel id"));
        }
```

The pull request #99 is an attempt to fix this.

**Comment by jcjones** [comment]
Thank you for this. Upstream patch at https://bugzilla.mozilla.org/show_bug.cgi?id=1609997
