### ISSUE TITLE
Fails to build on s390x

### ISSUE THREAD

**Issue by ricotz** [mozilla/authenticator-rs#105]
Due to missing authenticator-rs/src/linux/ioctl_s390x.rs

Please generate and add the s390x (and more missing) arch-specific type-definitions to provide build-support on those archs.

**Comment by msirringhaus** [comment]
I would provide a PR for s390x. Unfortunately, its not documented anywhere how to generate `authenticator-rs/src/linux/ioctl_s390x.rs` (or at least I couldn't find it).

**Comment by msirringhaus** [comment]
Nevermind, figured it out.
Ran `cargo build --features binding-recompile`, then `cargo build` and `cargo test`
