### ISSUE TITLE
No ioctl bindings for ppc64 BE, breaking FF 74 build

### ISSUE THREAD

**Issue by q66** [mozilla/authenticator-rs#108]
There is ppc64 LE support in https://github.com/mozilla/authenticator-rs/blob/master/src/linux/ioctl_powerpc64le.rs, but not BE.

The ioctl numbers for BE are exactly the same. Is there even a reason to make them separate?

Anyway, FF74 fails to build. Just copying the file from `powerpc64le` to `powerpc64be` should fix it.

**Comment by jcjones** [comment]
Sorry about that. 

Yeah, the proliferation of the ioctl files maybe should be ... amended. Our decision to not generate them was expedient for avoiding a problem we were having with rust-bindgen, but maybe I should try fixing that instead again soon.

**Comment by q66** [comment]
I wonder if there even is a point in having some generation infra for these; these numbers are constant and are pretty much guaranteed to never change under the "we don't break userspace" principle of the Linux kernel - maybe it'd be best to just get them in for all platforms and be done with it?
