### ISSUE TITLE
Add back in `use io`

### ISSUE THREAD

**Issue by jcjones** [mozilla/authenticator-rs#139]
In [Bug 1666701](https://bugzilla.mozilla.org/show_bug.cgi?id=1666701), reporter indicates OpenBSD fails to compile due to `failed to resolve: use of undeclared type or module 'io'`. Those were removed in the clippy updates, and cross builds still worked, but apparently it was too much. 

Let's put those "unnecessary imports" back.

(edit: openBSD, not freeBSD)

**Comment by landryb** [comment]
That was OpenBSD fwiw.

**Comment by jcjones** [comment]
uplift: https://phabricator.services.mozilla.com/D92784
