### ISSUE TITLE
Creating an attestationObject from the registration output

### ISSUE THREAD

**Issue by vedran6** [mozilla/authenticator-rs#141]
I am struggling to understand what it takes to build an attestationObject field given the output of the `U2FManager::register` method. Is there a part of the output that  translates into said object? Or does the output need to be parsed and the object constructed piecemeal? It appears that attestationObject requires a device counter to be present and that doesn't seem to live in the [registration response.](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#registration-response-message-error-test-of-user-presence-required)

Any help would be greatly appreciated.

**Comment by jcjones** [comment]
Here is where this happens in Firefox:
https://searchfox.org/mozilla-central/source/dom/webauthn/U2FHIDTokenManager.cpp#275

The register method's response is put into `CryptoBuffer regData` which is [decomposed out of the U2F format](https://searchfox.org/mozilla-central/rev/25d5a4443a7e13cfa58eff38f1faa5e69f0b170f/dom/webauthn/WebAuthnUtil.cpp#279); as you say, if you're working toward the WebAuthn type, right now `authenticator-rs` doesn't form that, and [Firefox sets the counter to zero](https://searchfox.org/mozilla-central/rev/25d5a4443a7e13cfa58eff38f1faa5e69f0b170f/dom/webauthn/WebAuthnUtil.cpp#213-223) for U2F devices, which was the agreement and [codified in the webauthn spec as acceptable](https://w3c.github.io/webauthn/#sctn-sign-counter).

That said, having a means to return already-ready WebAuthn structures is something I would welcome a patch to do. One of the next major shifts in this API will be to add methods for WebAuthn-formatted responses to the API, which will need that construction when interacting with U2F devices, if you feel up to coding it. If not, I'll be getting there in the next few months, too.

**Comment by vedran6** [comment]
Excellent resources. I was able to construct a valid attestationObject by looking at the links above.

Thanks again, and hopefully I'll be able to contribute something back eventually.
