### ISSUE TITLE
Add a C API for the WebDriver service

### ISSUE THREAD

**Issue by jcjones** [mozilla/authenticator-rs#144]
For Gecko to use the WebDriver feature, Gecko needs to be able to trigger `manager.add_webdriver_virtual_bus();` and potentially may need to provide a port (which would be a refactor).

Add such an API after determining what Gecko actually needs.

**Comment by jschanck** [comment]
Gecko is going to use XPCOM instead of a C API. There's nothing to do on the authenticator-rs side for that work.
