### ISSUE TITLE
offset_of is unsound

### ISSUE THREAD

**Issue by RalfJung** [mozilla/authenticator-rs#147]
The macro at https://github.com/mozilla/authenticator-rs/blob/660a701b45977cb5d184380061dfc8cec4f696be/src/windows/winapi.rs#L66 is unsound and causes UB due to using `*` on a NULL pointer. See [the reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) for details.

The [memoffset crate](https://github.com/Gilnaa/memoffset/) provides a version of this macro that avoids UB (on older versions of rustc, this is not always possible, so it falls back to the 'least incorrect' version when needed).

**Comment by rmartinho** [comment]
This was fixed by #171
