### ISSUE TITLE
ctap2 support - open falsely closed issue #33

### ISSUE THREAD

**Issue by Erik1000** [mozilla/authenticator-rs#151]
Firefox still hasn’t got full ctap2 support (especially for operations which require a pin). There’s an old issue #33 to support it but it seems like the issue was closed falsely because support is still not implemented. The old maintainer isn’t at Mozilla anymore. For further information look at the old #33 issue.

**Comment by Erik1000** [comment]
A maintainer should look at #150 and #148. If it is okay, it would be good to merge #150.

**Comment by dveditz** [comment]
reopened #33. Supporting CTAP2 in authenticator-rs will go a long way to gettting support into Firefox, but there are tracking bugs over in bugzilla, too, because there will be work done on that end as well. Maybe that's what JC was thinking about when he closed the other one.
