### ISSUE TITLE
`credBlob` example

### ISSUE THREAD

**Issue by tarun14110** [mozilla/authenticator-rs#156]
Do you support the `credBlob` extension? Is there any example or test case that I can use to try `credBlob` extension for the FIDO2 registration with my yubikey security key.

**Comment by msirringhaus** [comment]
Currently, no. `credBlob` was introduced with CTAP2.1. The main branch of this repo only supports CTAP1. 
CTAP2.0 is currently in the works, but that still doesn't have the extension.

**Comment by tarun14110** [comment]
Thanks for the response. Does Firefox use this implementation for `CTAP` protocol or it has its own implementation?

**Comment by msirringhaus** [comment]
Firefox is using this crate for talking to hardware tokens: https://searchfox.org/mozilla-central/source/third_party/rust/authenticator
