### ISSUE TITLE
support for using platform apis

### ISSUE THREAD

**Issue by dvc94ch** [mozilla/authenticator-rs#170]
looks like android, apple and windows have their own platform apis that should be used. not sure if there is some kind of dbus api on linux systems.

- [0] https://developers.google.com/identity/fido/android/native-apps
- [1] https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys
- [2] https://docs.microsoft.com/en-us/windows/uwp/security/microsoft-passport

**Comment by complexspaces** [comment]
FWIW, I don't think that Apple and Android's APIs can be plugged in to something like this library. Both of them require some kind of "context" to the active view presentation.

**Comment by dvc94ch** [comment]
That's what the ndk-context crate is for on android. not sure about ios.

**Comment by dveditz** [comment]
This library was created to do the low-level communication with a security token, not as a generic platform interface. I can see how that would be useful, but we think that should be a separate interface that implements the various platform hooks and then could call `authenticator-rs` (or equivalent) when those interfaces weren't available.

Where the platform interfaces are available you don't need this crate at all: the platform itself does the low-level talking to a security token.
