### ISSUE TITLE
Not-selected tokens should stop blinking when one completes

### ISSUE THREAD

**Issue by jcjones** [mozilla/authenticator-rs#34]
Right now, tokens that you don't touch continue blinking until the timeout completes, while the one you do touch stops blinking immediately. They should all stop.

**Comment by pzboyz** [comment]
Do you have a proposed solution? Would that be new U2F command or an extra parameter to an existing command?

**Comment by jcjones** [comment]
I think this is a change to the state machine(s), probably in each platform's `mod.rs`, perhaps calling a different u2f wire-protocol function on the way out of the loop.

@ttaubert, do you agree?

**Comment by ttaubert** [comment]
Yeah, that's probably where that belongs.
