### ISSUE TITLE
broken on linux ppc64le, arm64, and probably other archs as well

### ISSUE THREAD

**Issue by estokes** [mozilla/authenticator-rs#96]
in linux/hidraw.rs bits are copied from the x86_64 version of /usr/include/asm-generic/ioctl.h which are non portable to other architectures, as a result on non x86_64 architectures the ioctl command is incorrect, and as a result we never find they key. for example,

**x86_64**

    _IOC_NRBITS: 8
    _IOC_TYPEBITS: 8
    _IOC_SIZEBITS: 14
    _IOC_DIRBITS: 2
    _IOC_NRSHIFT: 0
    _IOC_TYPESHIFT: 8
    _IOC_SIZESHIFT: 16
    _IOC_DIRSHIFT: 30
    HIDIOCGRDESCSIZE: 2147764225
    HIDIOCGRDESC: 2416199682

**ppc64le**

    _IOC_NRBITS: 8
    _IOC_TYPEBITS: 8
    _IOC_SIZEBITS: 13
    _IOC_DIRBITS: 3
    _IOC_NRSHIFT: 0
    _IOC_TYPESHIFT: 8
    _IOC_SIZESHIFT: 16
    _IOC_DIRSHIFT: 29
    HIDIOCGRDESCSIZE: 1074022401
    HIDIOCGRDESC: 1342457858

**arm64**

    _IOC_NRBITS: 8
    _IOC_TYPEBITS: 8
    _IOC_SIZEBITS: 14
    _IOC_DIRBITS: 2
    _IOC_NRSHIFT: 0
    _IOC_TYPESHIFT: 8
    _IOC_SIZESHIFT: 16
    _IOC_DIRSHIFT: 30
    HIDIOCGRDESCSIZE: -2147203071
    HIDIOCGRDESC: -1878767614

Instead of trying to reconstruct a macro and it's values for all archs it might be best to figure out a way to just read the value of HIDIOCGRDESCSIZE, and HIDIOCGRDESC from the C header files. Off the top of my head I don't know a great way to do this, other than constructing a small C program that we either link and call at runtime, or call during the build to fill in the values. The current solution seems like it could cause constant pain as/if these values ever change.

**Comment by awilfox** [comment]
Seems like https://github.com/rust-lang/libc/pull/1164 may be relevant as a possible solution.

**Comment by estokes** [comment]
This is on ppc64le, so it is little endian. I'm going to try to get bindgen spun up to just read the C headers.

**Comment by awilfox** [comment]
I'm sorry, I pasted the wrong link!

I meant: https://github.com/AdelieLinux/libc/blob/06bf363e13032fa84abadfca11178562cce19bff/src/unix/notbsd/linux/musl/b64/mod.rs#L326

```#[cfg(target_arch = "powerpc64")]``` _et al_ could work for defining those constants properly.

**Comment by estokes** [comment]
Yes, that is one approach to the problem. The issue with it is that it would still essentially be copying information out of header files that are produced by the kernel, and could be updated at some point. If that happened all C based software would work fine, but authenticator would break again. It seems like quite a simple use of bindgen to just pull the values from the header at build time. I will be submitting a pull request for that as soon as I get it cleaned up and nice.

**Comment by jcjones** [comment]
Thank you for the report and the fix!
